# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-hello-world-test',
                'doc_host': 'https://hrmnjt.github.io',
                'git_url': 'https://github.com/hrmnjt/nbdev-hello-world-test',
                'lib_path': 'nbdev_hello_world_test'},
  'syms': {'nbdev_hello_world_test.core': {'nbdev_hello_world_test.core.foo': ('core.html#foo', 'nbdev_hello_world_test/core.py')}}}